In [11]:
import torch
import numpy as np

# Data formats

In [4]:
x = torch.Tensor(5,3) # We get zeros
print(x)

In [7]:
x = torch.rand(5,3)
print(x)


 0.3740  0.4492  0.5383
 0.5375  0.6355  0.5696
 0.3532  0.6830  0.7254
 0.6832  0.7883  0.9235
 0.7135  0.9151  0.2824
[torch.FloatTensor of size 5x3]



In [8]:
print(x.size())

torch.Size([5, 3])


## Some different addition methods

In [18]:
y = torch.rand(5,3)
d = torch.add(x,y)
print(d)
print(x+y)
print(x.add_(y))


 2.3725  1.9350  1.6198
 1.3181  2.2944  0.9796
 2.7434  2.5687  1.9370
 2.4791  2.0813  2.9663
 1.3094  2.0754  0.7034
[torch.FloatTensor of size 5x3]


 2.3725  1.9350  1.6198
 1.3181  2.2944  0.9796
 2.7434  2.5687  1.9370
 2.4791  2.0813  2.9663
 1.3094  2.0754  0.7034
[torch.FloatTensor of size 5x3]


 2.3725  1.9350  1.6198
 1.3181  2.2944  0.9796
 2.7434  2.5687  1.9370
 2.4791  2.0813  2.9663
 1.3094  2.0754  0.7034
[torch.FloatTensor of size 5x3]



### Hoorah, numpy style indexing

In [19]:
print(x[:,1])


 1.9350
 2.2944
 2.5687
 2.0813
 2.0754
[torch.FloatTensor of size 5]



In [21]:
b = x.numpy()
print(b)

[[ 2.37249207  1.9350493   1.6197542 ]
 [ 1.31814766  2.29443789  0.9796406 ]
 [ 2.7434206   2.56872249  1.93701816]
 [ 2.47908545  2.08134151  2.96629238]
 [ 1.309443    2.07542849  0.70344621]]


Note that numpy matrices created in this fashion will automatically update their torch counterparts:

In [22]:
b+=1

In [23]:
print(x)


 3.3725  2.9350  2.6198
 2.3181  3.2944  1.9796
 3.7434  3.5687  2.9370
 3.4791  3.0813  3.9663
 2.3094  3.0754  1.7034
[torch.FloatTensor of size 5x3]



### GPU: move location

if torch.cuda.is_available():
    x = x.cuda()
    

# Autograd
`Variables` are used to wrap tensors, and supports the majority of operations you want to compute upon your tensor, including returning the gradients via the `backwards` method.

In [26]:
from torch.autograd import Variable

In [47]:
x = Variable(torch.ones(2,2), requires_grad=True)

In [48]:
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [49]:
y = x + 2
print(y)
y.retain_grad()

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [50]:
print(y.grad_fn)

In [51]:
z = y * y * 3
out = z.mean()

print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [52]:
out.backward() # This propagates gradients backwards to the input variables

In [53]:
print(x.grad) # this corresponds to d(out)/dx

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [54]:
print(z.grad)
print(y.grad) 

None
Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



See [here](https://discuss.pytorch.org/t/why-cant-i-see-grad-of-an-intermediate-variable/94/11): the gradients of intermediate variables are immediately discarded during backprop to save memory.

You can use `.retain_grad()` on an intermediate variable to retain it!